import Head from 'next/head'
import Image from 'next/image'
import { BannerCarousel } from '../components/BannerCarousel'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container} >
      <Head>
        <title>STW - Study Travels Works</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main} style={{background:"url('/images/Fundo.png')", backgroundRepeat:"no-repeat", backgroundSize:"cover"}}>
      <header className={styles.header}>
          <Image src="/images/logo.png" alt="stw Logo" width={150} height={45} />
          <h1>
            More, trabalhe e estude no país mais escolhido por quem<br/>
            decide morar na Europa.
          </h1>
        </header>
        <div className={styles.mainFormVideo}>
            <div className={styles.form}>
              <h3>Agende agora<br/>
              um consulta gratuita</h3>
              <form>  
                <input type="text" placeholder='Nome' />  
                <input type="email" placeholder='Email' />  
                <input type="text" placeholder='Telefone     (+55) 00 00000-0000'/>
                  
              <select>
                <option selected disabled>Selecione o serviço de interesse</option>
                  <option>Arrendamentos e alojamento</option>
                  <option>Tramites Legais</option>
                  <option>Personal Shopper</option>
                  <option>Matricula em instituições de Ensino</option>
                  <option>Transfer | Deslocamento</option>
                  <option>Procura de Estagio ou Trabalho</option>
              </select>
              <button>Enviar mensagem</button>
              </form>
            </div>
          
            <iframe className={styles.video} src="https://player.vimeo.com/video/751205972?h=75b80bbe82&autoplay=1&title=0&portrait=0" frameborder="0" allow="autoplay; picture-in-picture" allowfullscreen>
              
            </iframe>
        </div>

      </main>
      <div className={styles.containerdefault}>
            <h2>Veja o que nossos clientes estão falando:</h2>
            <div>
            <BannerCarousel />
            </div>
      </div>
      <footer className={styles.footer}>
          <div>
              <div>
              <Image src="/images/logowhite.png" alt="stw Logo" width={150} height={45} />
              </div>
              <div className={styles.icons}>
                <a href="https://www.instagram.com/stw.pt/" target="_blank">
                  <Image src="/images/insta.png" alt="stw Logo" width={45} height={45} /> 
                  </a>
                <a>
                  <Image src="/images/twitter.png" alt="stw Logo" width={45} height={45} />
                </a>
                <a href="https://www.facebook.com/stw.portuguese/" target="_blank">
                <Image src="/images/face.png" alt="stw Logo" width={45} height={45} />
                </a>
                <a href="https://www.linkedin.com/company/study-travel-work-portuguese/mycompany/" target="_blank">
                <Image src="/images/linkedin.png" alt="stw Logo" width={45} height={45} />
                </a>

              </div>
          </div>
      </footer>
    </div>
  )
}
